module ChatopsDeployer
  WORKSPACE = ENV['DEPLOYER_WORKSPACE'] || '/var/www'
  DEPLOYER_HOST = ENV['DEPLOYER_HOST'] || '127.0.0.1.xip.io'
  NGINX_SITES_ENABLED_DIR = ENV['NGINX_SITES_ENABLED_DIR'] || '/etc/nginx/sites-enabled'
  LOG_FILE = ENV['DEPLOYER_LOG_FILE'] || '/var/log/chatops_deployer.log'
  COPY_SOURCE_DIR = ENV['DEPLOYER_COPY_SOURCE_DIR'] || '/etc/chatops_deployer/copy'
  LOG_URL = ENV['DEPLOYER_LOG_URL']
  GITHUB_WEBHOOK_SECRET = ENV['GITHUB_WEBHOOK_SECRET']
  GITHUB_OAUTH_TOKEN = ENV['GITHUB_OAUTH_TOKEN']
  DEFAULT_POST_URL = ENV['DEPLOYER_DEFAULT_POST_URL']
  DATA_CONTAINER_NAME = ENV['DEPLOYER_DATA_CONTAINER_NAME'] || 'cache'
  DATA_CONTAINER_VOLUME = ENV['DEPLOYER_DATA_CONTAINER_VOLUME'] || '/cache'
end

